server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5431/postgres
    username: postgres
    password: postgres
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL82Dialect
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.yaml
  messages:
    basename: messages

logging:
  level:
    liquibase: info